image: docker:latest

stages:
- build
- modify-deploy-repo

build-staging:
  stage: build
  except:
  - tags
  services:
  - docker:dind
  script:
  - apk add --no-cache curl jq python py-pip
  - pip install awscli
  - $(aws ecr get-login --no-include-email --region eu-west-1)
  - docker build -t ${STAGING_DOCKER_REGISTRY}/${CI_PROJECT_NAME}:${CI_COMMIT_SHA} .
  - docker push ${STAGING_DOCKER_REGISTRY}/${CI_PROJECT_NAME}:${CI_COMMIT_SHA}
  - cat $STAGING_GCP_TOKEN | docker login -u _json_key --password-stdin https://gcr.io
  - docker tag ${STAGING_DOCKER_REGISTRY}/${CI_PROJECT_NAME}:${CI_COMMIT_SHA} ${STAGING_GCP_DOCKER_REGISTRY}/${CI_PROJECT_NAME}:${CI_COMMIT_SHA}
  - docker push ${STAGING_GCP_DOCKER_REGISTRY}/${CI_PROJECT_NAME}:${CI_COMMIT_SHA}

build-tag:
  stage: build
  only:
  - tags
  services:
  - docker:dind
  script:
    - apk add --no-cache curl jq python py-pip
    - pip install awscli
    - $(aws ecr get-login --no-include-email --region eu-west-1)
    - docker build -t ${PROD_DOCKER_REGISTRY}/${CI_PROJECT_NAME}:${CI_COMMIT_TAG} .
    - docker push ${PROD_DOCKER_REGISTRY}/${CI_PROJECT_NAME}:${CI_COMMIT_TAG}
    - cat $PROD_GCP_TOKEN | docker login -u _json_key --password-stdin https://gcr.io
    - docker tag ${PROD_DOCKER_REGISTRY}/${CI_PROJECT_NAME}:${CI_COMMIT_TAG} ${PROD_GCP_DOCKER_REGISTRY}/${CI_PROJECT_NAME}:${CI_COMMIT_TAG}
    - docker push ${PROD_GCP_DOCKER_REGISTRY}/${CI_PROJECT_NAME}:${CI_COMMIT_TAG}

push-staging:
  image: alantang888/kubectl_git:0.3
  stage: modify-deploy-repo
  except:
  - tags
  script:
  - mkdir -p ~/.ssh
  - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
  - eval `ssh-agent -s`
  - chmod 600 $CI_RUNNER_SSH_PRIVATE
  - ssh-add $CI_RUNNER_SSH_PRIVATE
  - git clone git@gitlab.com:calipsa/kubernetes-infrastructure-staging.git
  - cd kubernetes-infrastructure-staging
  - yq w -i kubernetes/simple-http-request-display/deployment.yaml spec.template.spec.containers[0].image ${STAGING_DOCKER_REGISTRY}/${CI_PROJECT_NAME}:${CI_COMMIT_SHA}
  - cat kubernetes/${CI_PROJECT_NAME}/deployment.yaml
  - git add kubernetes/${CI_PROJECT_NAME}/deployment.yaml
  - git config --global user.name "${GITLAB_USER_NAME}"
  - git config --global user.email "${GITLAB_USER_EMAIL}"
  - git commit -m "Update ${CI_PROJECT_NAME} image to ${CI_COMMIT_SHA}"
  - git push
