image: atlassian/default-image:latest
pipelines:
  branches:
    "staging*":
    - step:
        name: build image for non-prod on AWS
        services:
        - docker
        script:
        - docker build -t ${APP_NAME}:latest .
        - pipe: atlassian/aws-ecr-push-image:1.1.2
          variables:
            AWS_ACCESS_KEY_ID: ${NON_PROD_AWS_ACCESS_KEY_ID}
            AWS_SECRET_ACCESS_KEY: ${NON_PROD_AWS_SECRET_ACCESS_KEY}
            AWS_DEFAULT_REGION: ${AWS_REGION}
            IMAGE_NAME: ${APP_NAME}
            TAGS: ${BITBUCKET_COMMIT}
    - step:
        name: modify staging k8s
        deployment: staging
        script:
        - pipe: calipsa/pipe-update-k8s-yaml:master
          variables:
            NEW_VERSION: ${BITBUCKET_COMMIT}
            GIT_REPO_PATH: calipsa/kubernetes-infrastructure-staging
            DOCKER_REGISTRY: ${STAGING_DOCKER_REGISTRY}


  tags:
    "**":
    - step:
        name: build image for tag on AWS
        services:
        - docker
        script:
        - docker build -t ${APP_NAME}:latest .
        - pipe: atlassian/aws-ecr-push-image:1.1.2
          variables:
            AWS_ACCESS_KEY_ID: ${PROD_AWS_ACCESS_KEY_ID}
            AWS_SECRET_ACCESS_KEY: ${PROD_AWS_SECRET_ACCESS_KEY}
            AWS_DEFAULT_REGION: ${AWS_REGION}
            IMAGE_NAME: ${APP_NAME}
            TAGS: ${BITBUCKET_TAG}
    - step:
        name: modify qa k8s
        deployment: qa
        script:
        - pipe: calipsa/pipe-update-k8s-yaml:master
          variables:
            NEW_VERSION: ${BITBUCKET_TAG}
            GIT_REPO_PATH: calipsa/kubernetes-infrastructure-qa
            DOCKER_REGISTRY: ${PROD_DOCKER_REGISTRY}
    - step:
        name: confirm deploy to production
        trigger: manual
        script:
        - echo "manual confirm to deploy"
    - step:
        name: modify prod k8s
        deployment: production
        script:
        - pipe: calipsa/pipe-update-k8s-yaml:master
          variables:
            NEW_VERSION: ${BITBUCKET_TAG}
            GIT_REPO_PATH: calipsa/kubernetes-infrastructure-production
            DOCKER_REGISTRY: ${PROD_DOCKER_REGISTRY}

